name: CI (Build, Security Scan, Test)

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      # Optional: ZAP wants an HTTP target; we run the Flask app directly.
      # For real deployments, add docker-compose / staging URL.
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest bandit pip-audit

      - name: SAST (Bandit)
        run: bandit -r backend/app -lll

      - name: Dependency scan (pip-audit)
        run: pip-audit -r backend/requirements.txt

      - name: Unit tests
        run: pytest -q

      - name: Run app (background)
        run: |
          python backend/server.py &
          sleep 3

      - name: DAST (OWASP ZAP Baseline)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://localhost:5000"
          allow_issue_writing: false
